// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Peer is one connected member of the active session.
 */
export class Peer {
    /**
     * Creates a new Peer instance.
     * @param {Partial<Peer>} [$$source = {}] - The source object to create the Peer.
     */
    constructor($$source = {}) {
        if (!("virtualIP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virtualIP"] = "";
        }
        if (!("publicAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicAddr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Peer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Peer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Peer(/** @type {Partial<Peer>} */($$parsedSource));
    }
}

/**
 * Status is the snapshot pushed to the frontend, both on request and via the
 * periodic "status" event.
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("myIP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["myIP"] = "";
        }
        if (!("session" in $$source)) {
            /**
             * active session name, if this tray started it
             * @member
             * @type {string}
             */
            this["session"] = "";
        }
        if (!("peers" in $$source)) {
            /**
             * @member
             * @type {Peer[]}
             */
            this["peers"] = [];
        }
        if (!("busy" in $$source)) {
            /**
             * a connect/send is in flight
             * @member
             * @type {boolean}
             */
            this["busy"] = false;
        }
        if (!("receiving" in $$source)) {
            /**
             * a receive listener is running
             * @member
             * @type {boolean}
             */
            this["receiving"] = false;
        }
        if (!("transfer" in $$source)) {
            /**
             * latest file-transfer status line
             * @member
             * @type {string}
             */
            this["transfer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField3_0($$parsedSource["peers"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Peer.createFrom;
const $$createType1 = $Create.Array($$createType0);
