// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService is the bridge exposed to the frontend. It shells out to the blindspot
 * binary for connect (which needs privilege elevation) and calls the in-process
 * internal/transfer package directly for file send/receive, while reading the on-disk
 * session state directly for status and disconnect.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcceptRequest / DeclineRequest are invoked from the frontend panel buttons and from
 * the notification-response callback. Both deliver on the pending request's decision
 * channel; a late call (after timeout/cancel) is a harmless no-op.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function AcceptRequest(id) {
    return $Call.ByID(1028681348, id);
}

/**
 * CancelReceive cancels a pending receive, if one is running. Cancelling the context
 * unblocks the in-process Accept, whose goroutine then clears the receive state.
 * @returns {$CancellablePromise<void>}
 */
export function CancelReceive() {
    return $Call.ByID(3816120566);
}

/**
 * CancelSend aborts a pending outbound offer. The cancelled flag is set before the conn
 * is closed so the blocked response read observes it and clears silently instead of
 * reporting an error; closing the conn also makes the receiver's prompt dismiss (EOF).
 * @returns {$CancellablePromise<void>}
 */
export function CancelSend() {
    return $Call.ByID(3939382243);
}

/**
 * Connect runs `blindspot connect -s <session> -p <password> [-n] [-H <hostname>]`,
 * which triggers the UAC elevation + daemon launch and blocks until the session is
 * up (or fails). A non-empty hostname overrides the default rendezvous server. It
 * returns the final status line the CLI printed.
 * @param {string} session
 * @param {string} password
 * @param {boolean} isNew
 * @param {string} hostname
 * @returns {$CancellablePromise<string>}
 */
export function Connect(session, password, isNew, hostname) {
    return $Call.ByID(1698713851, session, password, isNew, hostname);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeclineRequest(id) {
    return $Call.ByID(4275373592, id);
}

/**
 * Disconnect signals the running daemon to stop (the same mechanism as
 * `blindspot disconnect`) and waits briefly for it to tear down.
 * @returns {$CancellablePromise<string>}
 */
export function Disconnect() {
    return $Call.ByID(1465381917);
}

/**
 * GetStatus returns the current session snapshot.
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(3800095171).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * MyIP returns this device's virtual IP, derived from the (cleartext) public key.
 * Works even when the identity is encrypted at rest. Empty if no identity exists.
 * @returns {$CancellablePromise<string>}
 */
export function MyIP() {
    return $Call.ByID(3702040876);
}

/**
 * SelectFile opens a native file picker and returns the chosen path (empty if the
 * user cancelled). Cancellation is not an error — it returns "" so the frontend
 * simply keeps the previous selection and nothing is logged.
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(3517471721);
}

/**
 * SendFile offers a file to a peer. It first asks the peer's control channel (:28126)
 * for consent; on accept it streams the file over :28125. If the peer has no control
 * listener (an older tray) it falls back to a direct send so mixed versions interoperate.
 * Blocks until the peer decides (or a timeout) and, on accept, for the transfer. A
 * failure is surfaced as the status line and returned with a nil error, matching the
 * prior behavior where transfer failures were reported without an exception.
 * @param {string} peerIP
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function SendFile(peerIP, filePath) {
    return $Call.ByID(1125472359, peerIP, filePath);
}

/**
 * StartReceive binds an in-process receive listener so the tray can keep serving while
 * it waits for an incoming file. Returning without error means the port is bound. A
 * goroutine runs the one-shot Accept, streaming progress into the transfer status and
 * pushing it to the frontend; when it completes the receive state clears so a later
 * StartReceive rebinds cleanly.
 * @param {boolean} here
 * @returns {$CancellablePromise<void>}
 */
export function StartReceive(here) {
    return $Call.ByID(1268368826, here);
}

/**
 * Version returns the blindspot version string.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(449630457);
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
