// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService is the bridge exposed to the frontend. It wraps the same commands a
 * user would run in a terminal — shelling out to the blindspot binary for the
 * operations that need privilege elevation or long-running transfer logic
 * (connect / send / receive), and reading the on-disk session state directly for
 * everything else.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelReceive kills a pending `receive` process, if one is running.
 * @returns {$CancellablePromise<void>}
 */
export function CancelReceive() {
    return $Call.ByID(3816120566);
}

/**
 * Connect runs `blindspot connect -s <session> -p <password> [-n]`, which triggers
 * the UAC elevation + daemon launch and blocks until the session is up (or fails).
 * It returns the final status line the CLI printed.
 * @param {string} session
 * @param {string} password
 * @param {boolean} isNew
 * @returns {$CancellablePromise<string>}
 */
export function Connect(session, password, isNew) {
    return $Call.ByID(1698713851, session, password, isNew);
}

/**
 * Disconnect signals the running daemon to stop (the same mechanism as
 * `blindspot disconnect`) and waits briefly for it to tear down.
 * @returns {$CancellablePromise<string>}
 */
export function Disconnect() {
    return $Call.ByID(1465381917);
}

/**
 * GetStatus returns the current session snapshot.
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(3800095171).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * MyIP returns this device's virtual IP, derived from the (cleartext) public key.
 * Works even when the identity is encrypted at rest. Empty if no identity exists.
 * @returns {$CancellablePromise<string>}
 */
export function MyIP() {
    return $Call.ByID(3702040876);
}

/**
 * SelectFile opens a native file picker and returns the chosen path (empty if the
 * user cancelled).
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(3517471721);
}

/**
 * SendFile runs `blindspot send <peerIP> <filePath>` and returns the CLI's final
 * line. Blocks for the duration of the transfer.
 * @param {string} peerIP
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function SendFile(peerIP, filePath) {
    return $Call.ByID(1125472359, peerIP, filePath);
}

/**
 * StartReceive launches `blindspot receive` in the background so the tray can keep
 * serving while it waits for an incoming file. Progress lines are streamed into the
 * transfer status and pushed to the frontend.
 * @param {boolean} here
 * @returns {$CancellablePromise<void>}
 */
export function StartReceive(here) {
    return $Call.ByID(1268368826, here);
}

/**
 * Version returns the blindspot version string.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(449630457);
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
